# -*- coding: utf-8 -*-
"""OFI_func.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KNTAVh6X2-Ksa-Aa7H1F2P9FYM7pXyNH
"""

import pandas as pd

def calc_ofi_features(df: pd.DataFrame, levels: int = 10, rolling_window: int = 50) -> pd.DataFrame:
  """
  This function would compute Best-level OFI, Multi-Level OFI, and Integrated OFI. Best-level OFI would be the stepping stone for the Cross-asset OFI

  Params:
    df: DF sorted by timestamp
    levels (int): number of book levels to include (default = 10 for L0-L9)
    rolling_window (int): Window size for Integrated OFI

  Returns:
    df: DF with new OFI feature columns added
  """

  # Best-level OFI, which is level 0
  df['d_bid_sz_00'] = df['bid_sz_00'].diff()
  df['d_ask_sz_00'] = df['ask_sz_00'].diff()
  df['ofi_best'] = df['d_bid_sz_00'] - df['d_ask_sz_00']

  #Multi-level OFI

  weights = [1 / (i + 1) for i in range(levels)]
  ofi_multi = pd.Series(0, index=df.index)

  for i in range(levels):
        bid_col = f'bid_sz_0{i}'
        ask_col = f'ask_sz_0{i}'
        dbid_col = f'd_{bid_col}'
        dask_col = f'd_{ask_col}'

        df[dbid_col] = df[bid_col].diff()
        df[dask_col] = df[ask_col].diff()

        ofi_multi += weights[i] * (df[dbid_col] - df[dask_col])

  df['ofi_multi'] = ofi_multi

  # Integrated OFI (Rolling sum of best-level OFI)
  df['ofi_integrated'] = df['ofi_best'].rolling(window=rolling_window, min_periods=1).sum()

  return df